import { NextRequest, NextResponse } from "next/server";

export const dynamic = "force-dynamic";

function base64UrlDecode(value: string): Uint8Array {
  const padded = value.replace(/-/g, "+").replace(/_/g, "/") + "===".slice((value.length + 3) % 4);
  const bytes = Buffer.from(padded, "base64");
  return new Uint8Array(bytes);
}

function timingSafeEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  let result = 0;
  for (let i = 0; i < a.length; i += 1) {
    result |= a[i] ^ b[i];
  }
  return result === 0;
}

async function verifySignature(
  secret: string,
  payload: string,
  signature: string
): Promise<boolean> {
  const encoder = new TextEncoder();
  const key = await crypto.subtle.importKey(
    "raw",
    encoder.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );
  const expected = await crypto.subtle.sign("HMAC", key, encoder.encode(payload));
  const expectedBytes = new Uint8Array(expected);
  const providedBytes = base64UrlDecode(signature);
  return timingSafeEqual(expectedBytes, providedBytes);
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ simulationId: string }> }
) {
  const { simulationId } = await params;

  const accountSlug = process.env.TENDERLY_ACCOUNT_SLUG;
  const projectSlug = process.env.TENDERLY_PROJECT_SLUG;
  const accessKey = process.env.TENDERLY_ACCESS_KEY;
  const secret = process.env.SIMULATION_NONCE_SECRET;

  if (!accountSlug || !projectSlug || !accessKey) {
    return NextResponse.json(
      { error: "Tenderly not configured" },
      { status: 500 }
    );
  }

  if (!simulationId || !/^[a-f0-9-]+$/i.test(simulationId)) {
    return NextResponse.json(
      { error: "Invalid simulation ID" },
      { status: 400 }
    );
  }

  // Verify HMAC signature — only URLs generated by /api/simulate are valid
  const sig = request.nextUrl.searchParams.get("sig");
  if (!secret || !sig || !(await verifySignature(secret, simulationId, sig))) {
    return NextResponse.json(
      { error: "Unauthorized" },
      { status: 403 }
    );
  }

  // Share the simulation publicly
  let url = `https://dashboard.tenderly.co/${accountSlug}/${projectSlug}/simulator/${simulationId}`;

  try {
    const shareResponse = await fetch(
      `https://api.tenderly.co/api/v1/account/${accountSlug}/project/${projectSlug}/simulations/${simulationId}/share`,
      {
        method: "POST",
        headers: { "X-Access-Key": accessKey },
      }
    );

    if (shareResponse.ok) {
      // Use the public shared URL
      url = `https://dashboard.tenderly.co/shared/simulation/${simulationId}`;
    }
  } catch {
    // Use fallback URL
  }

  return NextResponse.json({ url });
}
