/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/wrangler.toml --env-file=/dev/null --include-runtime=false --env-interface=CacheWorkerEnv workers/cache-worker-env.d.ts` (hash: b445ac285ff9efef4a4e13999844af78)
interface __BaseEnv_CacheWorkerEnv {
	VAULT_CACHE: KVNamespace;
	HISTORY: R2Bucket;
	LOGS: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./vault-cache");
	}
	interface Env extends __BaseEnv_CacheWorkerEnv {}
}
interface CacheWorkerEnv extends __BaseEnv_CacheWorkerEnv {}
