/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/wrangler.x-weekly-apy.toml --env-file=/dev/null --include-runtime=false --env-interface=XWeeklyApyEnv workers/x-weekly-apy-env.d.ts` (hash: f4e2aaf70e707b23ba6a71812e5dafdf)
interface __BaseEnv_XWeeklyApyEnv {
	SOCIAL_CACHE: KVNamespace;
	CLOUDFLARE_ACCOUNT_ID: "7f4f33bd3b9086164518eee1e9b8590a";
	SITE_URL: "https://yldfi.co";
	SOCIAL_RENDER_PATH: "/social/weekly-apy";
	X_WEEKLY_COPY: "Weekly yld vault yields are here\n\nAuto-compounding vaults for cvxCRV and cvgCVX.\n\nyldfi.co";
	X_DRY_RUN: "false";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./x-weekly-apy");
	}
	interface Env extends __BaseEnv_XWeeklyApyEnv {}
}
interface XWeeklyApyEnv extends __BaseEnv_XWeeklyApyEnv {}
