name: Setup DNS Record
on: workflow_dispatch

jobs:
  create-dns:
    runs-on: ubuntu-latest
    steps:
      - name: Create merkl.yldfi.co DNS record
        env:
          CF_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          curl -s -X POST "https://api.cloudflare.com/client/v4/zones/d2b6f2f38da276438b10ccce0e75e981/dns_records" \
            -H "Authorization: Bearer $CF_TOKEN" \
            -H "Content-Type: application/json" \
            --data '{"type":"AAAA","name":"merkl","content":"100::","proxied":true,"ttl":1}' | jq .
